{
 "title": "IoT Demo Dashboard",
 "description": "IoT Demo Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Message Count",
   "type": "stat",
   "description": "Message Count",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM sensor_data;"
    }
   ]
  },
  {
   "title": "Current Bucket Count",
   "type": "stat",
   "description": "Message Count",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM temperature_humidity_summary_minute\nWHERE\n  $__timeFilter(bucket);"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(bucket,$__interval),\n  device_id AS metric,\n  avg(avg_temp*1.9+32) AS \"avg_temp\"\nFROM temperature_humidity_summary_minute\nWHERE\n  $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "gauge",
   "description": "Average Humidity",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(bucket,$__interval),\n  device_id AS metric,\n  avg(avg_humidity) AS \"avg_humidity\"\nFROM temperature_humidity_summary_minute\nWHERE\n  avg_humidity > 0\n  AND avg_humidity < 100\n  AND $__timeFilter(bucket)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "graph",
   "description": "Average Humidity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(bucket),\n  device_id AS metric,\n  avg_humidity\nFROM temperature_humidity_summary_minute\nWHERE\n  $__timeFilter(bucket)\n  AND avg_humidity >= 0.0\n  AND avg_humidity <= 100.0\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "graph",
   "description": "Average Temperature",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(bucket),\n  device_id AS metric,\n  ((avg_temp * 1.9) + 32) AS avg_temp\nFROM temperature_humidity_summary_minute\nWHERE\n  $__timeFilter(bucket)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Air Quality: Smoke",
   "type": "graph",
   "description": "Average Air Quality: Smoke",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  device_id AS metric,\n  avg_smoke\nFROM air_quality_summary_minute\nWHERE\n  $__timeFilter(bucket)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Air Quality: LPG",
   "type": "graph",
   "description": "Average Air Quality: LPG",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  device_id AS metric,\n  avg_lpg\nFROM air_quality_summary_minute\nWHERE\n  $__timeFilter(bucket)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "description": "Light",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  device_id AS metric,\n  avg_light\nFROM light_summary_minute\nWHERE\n  $__timeFilter(bucket)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Air Quality: CO",
   "type": "graph",
   "description": "Average Air Quality: CO",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  device_id AS metric,\n  avg_co\nFROM air_quality_summary_minute\nWHERE\n  $__timeFilter(bucket)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Motion",
   "type": "graph",
   "description": "Motion",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  device_id AS metric,\n  avg_motion\nFROM motion_summary_minute\nWHERE\n  $__timeFilter(bucket)\nORDER BY 1,2"
    }
   ]
  }
 ]
}